apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: ecosystem
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: reviews-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          env:
            - name: PYTHONPATH
              value: /app/app