FROM python:3.12-slim

WORKDIR /app

COPY requirements-common.txt .
COPY requirements-development.txt .
RUN pip install --no-cache-dir -r requirements-common.txt -r requirements-development.txt

COPY . .

ENV PYTHONPATH=/app/app

CMD ["uvicorn", "app.index:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]