apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
  namespace: ecosystem
  labels:
    app: ws-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-gateway
  template:
    metadata:
      labels:
        app: ws-gateway
    spec:
      containers:
        - name: ws-gateway
          image: ws-gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
            - containerPort: 50051
          env:
            - name: PYTHONPATH
              value: /app/app